In [2]:
import pandas as pd
import matplotlib as plt
import warnings
import seaborn as sns
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('Clean_Dataset.csv')
df.head()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [4]:
df.drop(['Unnamed: 0','flight','duration'], axis = 1, inplace=True)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   airline           300153 non-null  str
 1   source_city       300153 non-null  str
 2   departure_time    300153 non-null  str
 3   stops             300153 non-null  str
 4   arrival_time      300153 non-null  str
 5   destination_city  300153 non-null  str
 6   class             300153 non-null  str
 7   days_left         300153 non-null  int64
 8   price             300153 non-null  int64
dtypes: int64(2), str(7)
memory usage: 20.6 MB

In [5]:
df['stops'] = df['stops'].map({'zero': 0, 'one':1 , 'two_or_more': 2})
from sklearn.preprocessing import LabelEncoder
cols= ['airline','source_city','departure_time','arrival_time','destination_city','class']
for col in cols:
    le=LabelEncoder()
    df[col]=le.fit_transform(df[col])

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   airline           300153 non-null  int64
 1   source_city       300153 non-null  int64
 2   departure_time    300153 non-null  int64
 3   stops             300153 non-null  int64
 4   arrival_time      300153 non-null  int64
 5   destination_city  300153 non-null  int64
 6   class             300153 non-null  int64
 7   days_left         300153 non-null  int64
 8   price             300153 non-null  int64
dtypes: int64(9)
memory usage: 20.6 MB

In [7]:
df.head()

,airline,source_city,departure_time,stops,arrival_time,destination_city,class,days_left,price
0,4,2,2,0,5,5,1,1,5953
1,4,2,1,0,4,5,1,1,5953
2,0,2,1,0,1,5,1,1,5956
3,5,2,4,0,0,5,1,1,5955
4,5,2,4,0,4,5,1,1,5955

In [8]:
from sklearn.model_selection import train_test_split
X = df.drop(['price'], axis = 1)
y = df['price']
X_train, X_test, y_train,  y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [9]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [10]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train_scaled, y_train)
lr.score(X_test_scaled, y_test)

0.9058896533658769

In [11]:
from sklearn.metrics import mean_absolute_error
y_pred = lr.predict(X_test_scaled)
mean_absolute_error(y_test, y_pred)

4548.094907437862

In [12]:
import pickle
pickle.dump(lr, open('model.pkl', 'wb'))